name: Publish Release

on:
  release:
    types: [published]

jobs:
  call-run-tests:
    uses: ./.github/workflows/run_tests.yml

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: call-run-tests
    permissions:
      contents: write
      id-token: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v6
      with:
        path: artifacts

    - name: Create tarballs for each artifact
      run: |
        mkdir -p dist
        for dir in artifacts/*; do
          if [ -d "$dir" ]; then
            name=$(basename "$dir")
            tar_path="dist/${name}.tar.gz"
            echo "Creating tarball $tar_path"
            tar -czf "$tar_path" -C "$dir" .
          fi
        done

    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: gh release upload '${{ github.ref_name }}' dist/*.tar.gz --repo '${{ github.repository }}'
